services:
  mongodb:
    image: mongo:7.0
    container_name: contract_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - contract_network

  redis:
    image: redis:7-alpine
    container_name: contract_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - contract_network

  backend:
    build: ./backend
    container_name: contract_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - MONGO_DB=${MONGO_DB}
      - REDIS_URL=${REDIS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}      # ✅ Use Gemini instead of OpenAI
      - GEMINI_MODEL=${GEMINI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}      # ✅ Use OpenAI instead of Gemini
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}      # ✅ Use Anthropic instead of OpenAI
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS}
    volumes:
      - ./backend:/app
      - contract_uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - contract_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: ./backend
    container_name: contract_celery
    restart: always
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - MONGO_DB=${MONGO_DB}
      - REDIS_URL=${REDIS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}      # ✅ Use Gemini instead of OpenAI
      - GEMINI_MODEL=${GEMINI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}      # ✅ Use OpenAI instead of Gemini
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}      # ✅ Use Anthropic instead of OpenAI
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
    volumes:
      - ./backend:/app
      - contract_uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - contract_network
    command: celery -A app.main.celery_app worker --loglevel=info
    
  frontend:
      build: ./frontend
      container_name: contract_frontend
      ports:
        - "3000:3000"
      environment:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      volumes:
        - ./frontend:/app
        - /app/node_modules
        - /app/.next
      depends_on:
        - backend
      networks:
        - contract_network

volumes:
  mongodb_data:
  contract_uploads:

networks:
  contract_network:
    driver: bridge
