version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: contract_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - contract_network

  redis:
    image: redis:7-alpine
    container_name: contract_redis
    ports:
      - "6379:6379"
    networks:
      - contract_network

  backend:
    build: ./backend
    container_name: contract_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - contract_uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - contract_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: ./backend
    container_name: contract_celery
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - contract_uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - contract_network
    command: celery -A app.main.celery_app worker --loglevel=info

  # frontend:
  #   build: ./frontend
  #   container_name: contract_frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     - backend
  #   networks:
  #     - contract_network

volumes:
  mongodb_data:
  contract_uploads:

networks:
  contract_network:
    driver: bridge